version: '3.9'

services:
  server:
    container_name: links-app-server
    build: .
    ports:
      - 3000:5000
    volumes:
      - .:/app
    networks:
      - default
    environment:
      - FLASK_ENV=development
    depends_on:
      - postgres

  postgres:
    container_name: links-app-postgres
    image: postgres:14.3-alpine
    ports:
      - 5432:5432
    networks:
      - default
    environment:
      - "POSTGRES_DB=${DB_DATABASE}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
