version: '3.9'

services:
  server:
    container_name: links-webapp-server
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    networks:
      - default
    environment:
      - FLASK_ENV=development
      - GUNICORN_CMD_ARGS=-w 1 --reload
    depends_on:
      - postgres

  postgres:
    container_name: links-webapp-postgres
    image: postgres:14.3-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - default
    environment:
      - "POSTGRES_DB=${DB_DATABASE}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
