version: '3.9'

services:
  web:
    container_name: links-webapp-web
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
    networks:
      - default
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - GUNICORN_CMD_ARGS=-w 1 --reload
    depends_on:
      - db

  db:
    container_name: links-webapp-db
    image: postgres:14.3-alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - default
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
