CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(50) NOT NULL,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS tags (
	id SERIAL PRIMARY KEY,
  title VARCHAR(50) UNIQUE NOT NULL,
	created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS links (
	id SERIAL PRIMARY KEY,
  url TEXT NOT NULL,
  tag_id INT NOT NULL,
  user_id INT NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL,
	FOREIGN KEY (tag_id) REFERENCES tags (id),
	FOREIGN KEY (user_id) REFERENCES users (id)
);
